version: '3'
services:
  couchdb:
    ports:
      - '5984:5984'
  proxy:
    ports:
      - '80:80'
      - '8081:8081'  # API/Dashboard
  flower:
    ports:
      - '5555:5555'
  backend:
    ports:
      - '8888:8888'  # Main backend port
  backend-tests:
    ports:
      - '8889:8888'  # Test service on different external port
