entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
          permanent: true

  web-secure:
    address: ":443"

  traefik:
    address: ":8080"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: true
    network: my_devops_demo_default

  file:
    directory: "/etc/traefik/dynamic_conf"
    watch: true

log:
  level: "DEBUG"

accessLog: {}