apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000        # Container port
      targetPort: 5000  # Target inside the container
      nodePort: 30007   # External port to access via minikube
